const EventTypes = Object.freeze({
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_REGISTER: 'AUTH_REGISTER',
  CONSENT_CREATED: 'CONSENT_CREATED',
  CONSENT_APPROVED: 'CONSENT_APPROVED',
  CONSENT_REJECTED: 'CONSENT_REJECTED',
  CONSENT_REVOKED: 'CONSENT_REVOKED',
  CONSENT_EXPIRED: 'CONSENT_EXPIRED',
  MDM_MATCH_FOUND: 'MDM_MATCH_FOUND',
  MDM_MANUAL_REVIEW_FLAGGED: 'MDM_MANUAL_REVIEW_FLAGGED',
  DATA_ACCESS: 'DATA_ACCESS',
  WORKFLOW_STEP_COMPLETED: 'WORKFLOW_STEP_COMPLETED',
  WORKFLOW_COMPLETED: 'WORKFLOW_COMPLETED',
  APPLICATION_CREATED: 'APPLICATION_CREATED',
  APPLICATION_APPROVED: 'APPLICATION_APPROVED',
  APPLICATION_REJECTED: 'APPLICATION_REJECTED',
  SYSTEM: 'SYSTEM',
});

const Exchanges = Object.freeze({
  CONSENT: 'maha.consent.events',
  WORKFLOW: 'maha.workflow.events',
  MDM: 'maha.mdm.events',
  AUDIT: 'maha.audit.events',
});

module.exports = { EventTypes, Exchanges };
