const WorkflowStates = Object.freeze({
  APPLICATION_RECEIVED: 'APPLICATION_RECEIVED',
  CONSENT_REQUESTED: 'CONSENT_REQUESTED',
  CONSENT_GRANTED: 'CONSENT_GRANTED',
  MDM_RESOLUTION: 'MDM_RESOLUTION',
  DATA_RETRIEVAL: 'DATA_RETRIEVAL',
  DATA_VALIDATION: 'DATA_VALIDATION',
  ELIGIBILITY_CHECK: 'ELIGIBILITY_CHECK',
  OFFICER_REVIEW: 'OFFICER_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CITIZEN_NOTIFIED: 'CITIZEN_NOTIFIED',
});

module.exports = { WorkflowStates };
